### ISSUE TITLE
Are this support IDA6.6 ?

### ISSUE THREAD

**Issue by abdilahrf** [zyantific/IDASkins#18] opened 2016-11-20 06:39 UTC
![image](https://cloud.githubusercontent.com/assets/6015012/20460993/99dbea5a-af26-11e6-90ca-98ef872f44ce.png)

the sciprt say can't found cmake , I am download latest from this github repo. Thanks

**Comment by athre0z** [comment] 2016-11-20 14:37
IDA plugins can't be built using MinGW, please use Visual Studio 2015 for IDA >= 6.9 or Visual Studio 2010 for older versions on Windows instead.

**Comment by athre0z** [comment] 2016-11-22 16:29
Alright, I'll close this for now. In case the issue isn't resolved, feel free to drop a comment below.

**Closed by athre0z** 2016-11-22 16:29 UTC

**Comment by abdilahrf** [comment] 2016-11-23 04:15
Hi @athre0z : i am using Visual Studio 2010 , but can't find where the main project to compile ... 
i just tough to built with the python script :/

**Comment by athre0z** [comment] 2016-11-23 04:54
Uff ... is there any reason not to use the [binaries we provide](https://github.com/zyantific/IDASkins/releases)? Building IDA plugins is a pain in the ass and I don't have the time to give you a detailed instructions on the how. You can use the Py script, just launch it from a Visual Studio shell and make sure CMake is installed and in the PATH as well. Besides, you'll have to download and build Qt 4.8.4 with some special switches to work with IDA ([see HR blog](http://www.hexblog.com/?p=250)).
