### ISSUE TITLE
"First Start" dialog causes IDA to crash if IDA_IPython is installed as well

### ISSUE THREAD

**Issue by tmr232** [zyantific/IDASkins#9] opened 2016-03-31 06:44 UTC
I have IDAIPython installed for quite a long time, and it is working well.
Today I decided to try IDASkins. After installing it, IDA kept crashing on startup when starting to show the "First Start" dialog.
The crash seems to be related to the Python interpreter state, so I disabled my only non-default Python plugin - IDAIPython. Once done, everything worked as expected.
After the first run, I enabled IDAIPython, and all seems to work well.

I did not have time to dig in and see if this is a bug in IDAIPython or IDASkins, so I am opening an issue there as well, and referencing this one.

**Comment by athre0z** [comment] 2016-03-31 12:39
Thanks for the report. Could you please provide a little more information about your installation? What OS? What version of IDA? idaq or idaq64?

**Comment by tmr232** [comment] 2016-03-31 12:43
Windows 10x64
IDA 6.9
idaq
latest IDAIPython

**Comment by athre0z** [comment] 2016-03-31 13:25
Thanks, I can reproduce the issue.
![devenv_2016-03-31_15-19-34](https://cloud.githubusercontent.com/assets/6553158/14176998/4caa3f50-f754-11e5-8636-1fd62ca599da.png)
Considering IDASkins doesn't link against nor interacts with the Python RT and looking at the stack-trace, I'd say it's a use-before-init / race-condition in the IPython plugin.

**Comment by james91b** [comment] 2016-04-02 06:32
I couldn't re-produce it on my version. However, looking at the stack trace it seems to be because of a the call to PyGILState_Ensure before python is loaded correctly. Definitely an ida_ipyhton issue. I think we can close the issue here.

**Closed** 2016-04-02 11:56 UTC
