### ISSUE TITLE
IDA keeps asking me that theme is not set after every start

### ISSUE THREAD

**Issue by norey** [zyantific/IDASkins#49] opened 2018-11-06 15:48 UTC
I keep getting this message

![msg](https://i.imgur.com/fWNsTzn.png)

Whenever I start IDA, and when selecting "Yes" I don't get a window for selecting a theme. I have to go to the plugins menu and do it from there.

This is on macOS Mojave

```
$ ls /Applications/IDA\ Pro\ 7.2/idabin/plugins/idaskins
__init__.py		objectinspector.py	settings.py		themes
__init__.pyc		objectinspector.pyc	settings.pyc		themeselector.py
idafontconfig.py	plugin.py		thememanifest.py	themeselector.pyc
idafontconfig.pyc	plugin.pyc		thememanifest.pyc	ui
$ ls /Applications/IDA\ Pro\ 7.2/idabin/plugins/idaskins.py 
/Applications/IDA Pro 7.2/idabin/plugins/idaskins.py
```

**Comment by athre0z** [comment] 2018-11-06 16:22
Duplicate of #42, issue is fixed on master. I'll release a new version with the fix included shortly.

**Closed by athre0z** 2018-11-06 16:22 UTC

**Comment by norey** [comment] 2018-11-06 16:23
Sorry about that, should have checked closed issues.
